version: '3.8'

services:
  app:
    build: .
    container_name: app-node
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3308/registro
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro
    ports:
      - "3308:3306"  # Puerto 330 en host -> 3306 en contenedor
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
